// frontend/src/components/ui/input.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

/* Presentational text input. Styling comes entirely from tokens (--input, --ring). */
const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(
  ({ className, type = "text", ...props }, ref) => {
    return (
      <input
        ref={ref}
        type={type}
        className={cn(
          "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
          className,
        )}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };

// resources/js/components/ui/Input.vue
<script setup lang="ts">
import { cn } from '@/lib/cn';

const props = defineProps<{
    /** v-model value. */
    modelValue?: string | number | null;
    id?: string;
    type?: string;
    /** Renders the error ring and links the message for assistive tech. */
    invalid?: boolean;
    class?: string;
}>();

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();

function onInput(event: Event): void {
    emit('update:modelValue', (event.target as HTMLInputElement).value);
}
</script>

<template>
    <input
        :id="id"
        :type="type ?? 'text'"
        :value="modelValue ?? ''"
        :aria-invalid="invalid || undefined"
        :class="
            cn(
                'flex h-10 w-full rounded-lg border bg-card px-3 py-2 text-sm transition-colors',
                'placeholder:text-muted-foreground',
                'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background',
                'disabled:cursor-not-allowed disabled:opacity-50',
                invalid ? 'border-destructive focus-visible:ring-destructive' : 'border-input',
                props.class,
            )
        "
        @input="onInput"
    />
</template>
