// frontend/src/components/ui/mention-input.tsx
"use client";

import * as React from "react";
import { createPortal } from "react-dom";

import { cn } from "@/lib/utils";

export interface MentionMember {
  user_id: string;
  name: string;
  email?: string;
}

const MAX_RESULTS = 8;

/**
 * A textarea with inline `@`-mention autocomplete. Typing `@` (at the start or
 * after whitespace) opens a portal dropdown of team members; arrow keys move,
 * Enter/Tab selects, Escape dismisses. Selecting inserts `@Name ` into the text
 * and reports the set of mentioned user_ids (those whose token is still present)
 * via onMentionsChange.
 */
export function MentionInput({
  value,
  onChange,
  onMentionsChange,
  members,
  placeholder,
  disabled,
  rows = 3,
  id,
  "aria-label": ariaLabel,
}: {
  value: string;
  onChange: (value: string) => void;
  onMentionsChange?: (userIds: string[]) => void;
  members: MentionMember[];
  placeholder?: string;
  disabled?: boolean;
  rows?: number;
  id?: string;
  "aria-label"?: string;
}) {
  const taRef = React.useRef<HTMLTextAreaElement>(null);
  const mentioned = React.useRef<Map<string, string>>(new Map()); // user_id -> inserted name
  const pendingCaret = React.useRef<number | null>(null);

  const [query, setQuery] = React.useState<string | null>(null);
  const [anchor, setAnchor] = React.useState(0);
  const [highlight, setHighlight] = React.useState(0);
  const [pos, setPos] = React.useState<{
    top: number;
    left: number;
    width: number;
    maxHeight: number;
  } | null>(null);

  const filtered = React.useMemo(() => {
    if (query === null) return [];
    const q = query.toLowerCase();
    return members
      .filter((m) => m.name.toLowerCase().includes(q) || (m.email ?? "").toLowerCase().includes(q))
      .slice(0, MAX_RESULTS);
  }, [query, members]);

  const open = query !== null && filtered.length > 0;

  // Detect an active "@token" immediately before the caret (no whitespace in it).
  function detect(text: string, caret: number) {
    const upto = text.slice(0, caret);
    const at = upto.lastIndexOf("@");
    if (at === -1) return setQuery(null);
    const before = at === 0 ? "" : upto[at - 1];
    const token = upto.slice(at + 1);
    if ((at === 0 || /\s/.test(before)) && !/\s/.test(token)) {
      setAnchor(at);
      setQuery(token);
      setHighlight(0);
    } else {
      setQuery(null);
    }
  }

  function emitMentions(text: string) {
    if (!onMentionsChange) return;
    const ids = new Set<string>();
    for (const [uid, name] of mentioned.current) {
      if (text.includes(`@${name}`)) ids.add(uid);
    }
    onMentionsChange([...ids]);
  }

  function handleChange(e: React.ChangeEvent<HTMLTextAreaElement>) {
    const text = e.target.value;
    onChange(text);
    detect(text, e.target.selectionStart ?? text.length);
    emitMentions(text);
  }

  function selectMember(m: MentionMember) {
    const caret = taRef.current?.selectionStart ?? value.length;
    const before = value.slice(0, anchor);
    const after = value.slice(caret);
    const insert = `@${m.name} `;
    const next = before + insert + after;
    mentioned.current.set(m.user_id, m.name);
    pendingCaret.current = before.length + insert.length;
    onChange(next);
    setQuery(null);
    emitMentions(next);
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (!open) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setHighlight((h) => (h + 1) % filtered.length);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setHighlight((h) => (h - 1 + filtered.length) % filtered.length);
    } else if (e.key === "Enter" || e.key === "Tab") {
      e.preventDefault();
      selectMember(filtered[Math.min(highlight, filtered.length - 1)]);
    } else if (e.key === "Escape") {
      e.preventDefault();
      setQuery(null);
    }
  }

  // Restore the caret after a programmatic insert; clear tracked mentions when emptied.
  React.useEffect(() => {
    if (pendingCaret.current !== null && taRef.current) {
      const c = pendingCaret.current;
      taRef.current.focus();
      taRef.current.setSelectionRange(c, c);
      pendingCaret.current = null;
    }
    if (value === "") mentioned.current.clear();
  }, [value]);

  // Anchor the dropdown under the textarea via a portal so it never clips.
  const updatePosition = React.useCallback(() => {
    const el = taRef.current;
    if (!el) return;
    const r = el.getBoundingClientRect();
    const spaceBelow = window.innerHeight - r.bottom - 8;
    setPos({ top: r.bottom + 4, left: r.left, width: r.width, maxHeight: Math.max(140, spaceBelow) });
  }, []);

  React.useLayoutEffect(() => {
    if (!open) return;
    updatePosition();
    window.addEventListener("resize", updatePosition);
    window.addEventListener("scroll", updatePosition, true);
    return () => {
      window.removeEventListener("resize", updatePosition);
      window.removeEventListener("scroll", updatePosition, true);
    };
  }, [open, updatePosition]);

  return (
    <div className="relative">
      <textarea
        ref={taRef}
        id={id}
        aria-label={ariaLabel}
        rows={rows}
        value={value}
        disabled={disabled}
        placeholder={placeholder}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onBlur={() => window.setTimeout(() => setQuery(null), 100)}
        className="flex w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
      />
      {open &&
        pos &&
        createPortal(
          <ul
            role="listbox"
            className="fixed z-50 overflow-auto rounded-md border border-border bg-popover p-1 shadow-md"
            style={{ top: pos.top, left: pos.left, width: pos.width, maxHeight: pos.maxHeight }}
          >
            {filtered.map((m, i) => (
              <li key={m.user_id}>
                <button
                  type="button"
                  role="option"
                  aria-selected={i === highlight}
                  // mousedown fires before the textarea blur, so selection still lands.
                  onMouseDown={(e) => {
                    e.preventDefault();
                    selectMember(m);
                  }}
                  onMouseEnter={() => setHighlight(i)}
                  className={cn(
                    "block w-full rounded-sm px-2 py-1.5 text-left text-sm",
                    i === highlight ? "bg-accent" : "hover:bg-accent",
                  )}
                >
                  <span className="font-medium">{m.name}</span>
                  {m.email && <span className="ml-2 text-xs text-muted-foreground">{m.email}</span>}
                </button>
              </li>
            ))}
          </ul>,
          document.body,
        )}
    </div>
  );
}

// resources/js/components/ui/MentionInput.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, useId, watch } from 'vue';

import { usePopover } from '@/composables/usePopover';
import { cn } from '@/lib/cn';

/**
 * A plain text field with inline `@`-mention autocomplete, ported from the
 * outgoing React app's `mention-input.tsx` (algorithm) onto this app's own
 * popover/dropdown conventions (`usePopover`, absolute-positioned — not a
 * portal, matching every other dropdown here since a fixed-position one
 * breaks under the iOS keyboard). A single-line `<input>`, not a `<textarea>`
 * — it's a drop-in for an existing input, styled by the caller via `class`,
 * not a new field of its own; `selectionStart`/`setSelectionRange` work
 * identically on either element, so nothing about the algorithm needs a
 * textarea.
 *
 * Typing `@` at the start of the text or right after whitespace opens a
 * dropdown of the tenant's members, filtered locally by name/email (the list
 * is small — fetched once, not searched server-side). Arrow keys move,
 * Enter/Tab inserts `@Name ` and tracks the mention out of band; deleting the
 * inserted text un-mentions them. `mentions` is recomputed from what's still
 * literally present in the text whenever it changes.
 */
export interface Mentionable {
    id: string;
    name: string;
    email: string;
}

const props = withDefaults(
    defineProps<{
        modelValue: string;
        members: Mentionable[];
        placeholder?: string;
        id?: string;
        ariaLabel?: string;
        class?: string;
    }>(),
    { placeholder: 'Write a comment…' },
);

const emit = defineEmits<{ 'update:modelValue': [string]; mentions: [string[]] }>();

const anchor = ref<HTMLElement | null>(null);
const input = ref<HTMLInputElement | null>(null);
const { open, show, close } = usePopover(anchor);
const listId = useId();

const query = ref<string | null>(null);
const anchorIndex = ref(0);
const activeIndex = ref(0);

/** user_id -> the name text that was inserted for them, so it can be found (or not) in later edits. */
const mentioned = new Map<string, string>();

const filtered = computed(() => {
    if (query.value === null) return [];

    const term = query.value.toLowerCase();

    return props.members
        .filter((m) => m.name.toLowerCase().includes(term) || m.email.toLowerCase().includes(term))
        .slice(0, 8);
});

watch(filtered, () => (activeIndex.value = 0));

/** An "@token" immediately before the caret — start of text, or right after whitespace, with no whitespace since. */
function detect(text: string, caret: number): void {
    const before = text.slice(0, caret);
    const at = before.lastIndexOf('@');

    if (at === -1) {
        query.value = null;

        return;
    }

    const precedingChar = at === 0 ? '' : before[at - 1];
    const token = before.slice(at + 1);

    if ((at === 0 || /\s/.test(precedingChar ?? '')) && !/\s/.test(token)) {
        anchorIndex.value = at;
        query.value = token;
        show();
    } else {
        query.value = null;
    }
}

function emitMentions(text: string): void {
    const ids = [...mentioned.entries()].filter(([, name]) => text.includes(`@${name}`)).map(([id]) => id);

    emit('mentions', ids);
}

function onInput(event: Event): void {
    const el = event.target as HTMLInputElement;

    emit('update:modelValue', el.value);
    detect(el.value, el.selectionStart ?? el.value.length);
    emitMentions(el.value);
}

function select(member: Mentionable): void {
    const el = input.value;
    const caret = el?.selectionStart ?? props.modelValue.length;
    const before = props.modelValue.slice(0, anchorIndex.value);
    const after = props.modelValue.slice(caret);
    const insert = `@${member.name} `;
    const next = before + insert + after;

    mentioned.set(member.id, member.name);
    emit('update:modelValue', next);
    emitMentions(next);
    close({ restoreFocus: false });
    query.value = null;

    const caretAt = before.length + insert.length;
    nextTick(() => {
        el?.focus();
        el?.setSelectionRange(caretAt, caretAt);
    });
}

function move(delta: number): void {
    if (filtered.value.length === 0) return;

    activeIndex.value = (activeIndex.value + delta + filtered.value.length) % filtered.value.length;
}

function onKeydown(event: KeyboardEvent): void {
    if (query.value === null || filtered.value.length === 0) return;

    switch (event.key) {
        case 'ArrowDown':
            event.preventDefault();
            move(1);
            break;
        case 'ArrowUp':
            event.preventDefault();
            move(-1);
            break;
        case 'Enter':
        case 'Tab': {
            const member = filtered.value[activeIndex.value];
            if (member === undefined) return;
            event.preventDefault();
            select(member);
            break;
        }
        case 'Escape':
            event.preventDefault();
            query.value = null;
            close({ restoreFocus: false });
            break;
    }
}

/** An emptied field has nothing left to mention. */
watch(
    () => props.modelValue,
    (value) => {
        if (value === '') mentioned.clear();
    },
);

onMounted(() => {
    if (props.modelValue === '') mentioned.clear();
});
</script>

<template>
    <div ref="anchor" class="relative min-w-0 flex-1">
        <input
            :id="id"
            ref="input"
            type="text"
            :value="modelValue"
            :placeholder="placeholder"
            :aria-label="ariaLabel"
            role="combobox"
            aria-autocomplete="list"
            :aria-expanded="open && filtered.length > 0"
            :aria-controls="listId"
            :class="cn('w-full bg-transparent focus-visible:outline-none', props.class)"
            @input="onInput"
            @keydown="onKeydown"
        />

        <ul
            v-if="open && filtered.length > 0"
            :id="listId"
            role="listbox"
            class="absolute bottom-full left-0 z-30 mb-1 max-h-56 w-64 overflow-y-auto border border-border bg-card shadow-lg"
        >
            <li v-for="(member, i) in filtered" :key="member.id">
                <button
                    type="button"
                    role="option"
                    :aria-selected="i === activeIndex"
                    class="flex w-full items-center gap-2 px-3 py-1.5 text-left text-xs transition-colors"
                    :class="i === activeIndex ? 'bg-muted' : 'hover:bg-muted/60'"
                    @mousedown.prevent="select(member)"
                    @mouseenter="activeIndex = i"
                >
                    <span class="font-medium">{{ member.name }}</span>
                    <span class="truncate text-muted-foreground">{{ member.email }}</span>
                </button>
            </li>
        </ul>
    </div>
</template>
