// resources/js/components/ui/StatCard.vue
<script setup lang="ts">
import { cn } from '@/lib/cn';

/**
 * A headline figure with a caption.
 *
 * `alert` reproduces the design's warning treatment (Figma `386:1673`): the
 * value turns red and a small red square appears top-right. It marks a figure
 * that is *true but wrong* — capital sitting idle, a return rate far below
 * what the stock value implies — so it should only be set from a real
 * condition, never to draw the eye.
 */
withDefaults(defineProps<{ label: string; value: string; hint?: string; alert?: boolean }>(), {
    alert: false,
});
</script>

<template>
    <div class="rounded-lg border border-border bg-card p-5">
        <div class="flex items-start justify-between gap-2">
            <p class="text-sm font-medium text-muted-foreground">{{ label }}</p>
            <span v-if="alert" class="mt-1 size-2 shrink-0 rounded-[1px] bg-destructive" aria-hidden="true" />
        </div>
        <p :class="cn('mt-2 text-2xl font-semibold tracking-tight tabular-nums', alert && 'text-destructive')">
            {{ value }}
        </p>
        <p v-if="hint" class="mt-1 text-xs text-muted-foreground">{{ hint }}</p>
    </div>
</template>

// frontend/src/components/dashboard/stat-card.tsx
"use client";

import * as React from "react";

import { cn } from "@/lib/utils";
import { Card } from "@/components/ui/card";

/**
 * Compact metric card: label + prominent value, with a small tinted icon in the
 * top-right. `accent` is a className for the icon tile (e.g.
 * "bg-rose-500/10 text-rose-500").
 */
export function StatCard({
  label,
  value,
  icon: Icon,
  accent,
  delayMs = 0,
}: {
  label: string;
  value: React.ReactNode;
  icon: React.ComponentType<{ className?: string }>;
  accent: string;
  delayMs?: number;
}) {
  return (
    <Card
      style={{ animationDelay: `${delayMs}ms` }}
      className={cn(
        "animate-fade-up border-border/60",
        "transition-all duration-300 ease-out hover:-translate-y-0.5 hover:shadow-md",
      )}
    >
      <div className="p-5">
        <div className="flex items-start justify-between gap-3">
          <p className="text-sm text-muted-foreground">{label}</p>
          <span className={cn("flex size-8 shrink-0 items-center justify-center rounded-lg", accent)}>
            <Icon className="size-4" />
          </span>
        </div>
        <p className="mt-3 text-2xl font-semibold tracking-tight tabular-nums">{value}</p>
      </div>
    </Card>
  );
}
