// frontend/src/app/(app)/inventory/page.tsx
"use client";

import * as React from "react";

import { ApiError } from "@/lib/api/client";
import { useInventory } from "@/hooks/use-inventory";
import { useTranslation } from "@/i18n/context";
import type { InventoryItem, Money } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";

function formatMoney(money: Money | null): string {
  if (!money) return "—";
  if (money.formatted) return money.formatted;
  return `${money.currency} ${money.amount}`;
}

export default function InventoryPage() {
  const { t } = useTranslation();
  const [search, setSearch] = React.useState("");
  const [debounced, setDebounced] = React.useState("");

  // Debounce the search input so we don't hit the API on every keystroke.
  React.useEffect(() => {
    const id = setTimeout(() => setDebounced(search), 300);
    return () => clearTimeout(id);
  }, [search]);

  const { data, isLoading, isError, error } = useInventory(
    debounced ? { search: debounced } : {},
  );

  const items = data?.data ?? [];

  return (
    <div className="space-y-6">
      <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold tracking-tight">{t("inventory.title")}</h1>
          <p className="text-sm text-muted-foreground">
            {data?.meta
              ? t("inventory.subtitleCount", { count: data.meta.total })
              : t("inventory.subtitleDefault")}
          </p>
        </div>
        <Input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder={t("inventory.searchPlaceholder")}
          className="sm:max-w-xs"
        />
      </header>

      {isLoading && (
        <div className="flex items-center justify-center py-16">
          <Spinner className="size-6 text-muted-foreground" />
        </div>
      )}

      {isError && (
        <Card>
          <CardContent className="py-8 text-center text-sm text-destructive">
            {error instanceof ApiError && error.status === 403
              ? t("inventory.errorForbidden")
              : t("inventory.errorGeneric")}
          </CardContent>
        </Card>
      )}

      {!isLoading && !isError && items.length === 0 && (
        <Card>
          <CardContent className="py-12 text-center text-sm text-muted-foreground">
            {t("inventory.empty")}
          </CardContent>
        </Card>
      )}

      {!isLoading && !isError && items.length > 0 && (
        <>
          {/* Mobile: stacked cards. */}
          <div className="space-y-3 md:hidden">
            {items.map((item) => (
              <MobileRow key={item.id} item={item} />
            ))}
          </div>

          {/* Desktop: table. */}
          <Card className="hidden overflow-hidden md:block">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b border-border bg-muted/50 text-left text-muted-foreground">
                  <tr>
                    <Th>{t("inventory.colName")}</Th>
                    <Th>{t("inventory.colSku")}</Th>
                    <Th>{t("inventory.colCategory")}</Th>
                    <Th className="text-right">{t("inventory.colStock")}</Th>
                    <Th className="text-right">{t("inventory.colPrice")}</Th>
                    <Th>{t("inventory.colStatus")}</Th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((item) => (
                    <tr key={item.id} className="border-b border-border last:border-0 hover:bg-muted/30">
                      <Td className="font-medium">{item.name}</Td>
                      <Td className="text-muted-foreground">{item.sku}</Td>
                      <Td>{item.category}</Td>
                      <Td className="text-right tabular-nums">
                        {item.current_stock} {item.unit}
                      </Td>
                      <Td className="text-right tabular-nums">{formatMoney(item.default_price)}</Td>
                      <Td>
                        <StatusBadges item={item} />
                      </Td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>
        </>
      )}
    </div>
  );
}

function MobileRow({ item }: { item: InventoryItem }) {
  return (
    <Card>
      <CardContent className="space-y-2 p-4">
        <div className="flex items-start justify-between gap-2">
          <div>
            <p className="font-medium">{item.name}</p>
            <p className="text-xs text-muted-foreground">{item.sku}</p>
          </div>
          <StatusBadges item={item} />
        </div>
        <div className="flex items-center justify-between text-sm text-muted-foreground">
          <span>{item.category}</span>
          <span className="tabular-nums">
            {item.current_stock} {item.unit} · {formatMoney(item.default_price)}
          </span>
        </div>
      </CardContent>
    </Card>
  );
}

function StatusBadges({ item }: { item: InventoryItem }) {
  const { t } = useTranslation();
  return (
    <div className="flex flex-wrap gap-1">
      <Badge variant={item.is_active ? "success" : "secondary"}>
        {item.is_active ? t("common.status.active") : t("common.status.inactive")}
      </Badge>
      {item.is_for_sale && <Badge variant="outline">{t("common.forSale")}</Badge>}
    </div>
  );
}

function Th({ children, className }: { children: React.ReactNode; className?: string }) {
  return <th className={`px-4 py-3 font-medium ${className ?? ""}`}>{children}</th>;
}

function Td({ children, className }: { children: React.ReactNode; className?: string }) {
  return <td className={`px-4 py-3 ${className ?? ""}`}>{children}</td>;
}

// resources/js/pages/Inventory/Index.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { router, usePage } from '@inertiajs/vue3';

import AppLayout from '@/layouts/AppLayout.vue';
import Badge from '@/components/ui/Badge.vue';
import Button from '@/components/ui/Button.vue';
import Input from '@/components/ui/Input.vue';
import { useAuth } from '@/composables/useAuth';
import { formatMoney } from '@/lib/money';
import type { InventoryFilters, InventoryItem } from '@/types/inventory';
import type { Paginated, SharedProps } from '@/types';

const props = defineProps<{ items: Paginated<InventoryItem>; filters: InventoryFilters }>();

const page = usePage<SharedProps>();
const { can } = useAuth();

const search = ref(props.filters.search ?? '');

/*
  Debounced server-side search. `replace` keeps the browser history from filling
  with a step per keystroke; `preserveState` keeps the input focused and its
  value intact while the partial reload is in flight.
*/
let timer: ReturnType<typeof setTimeout> | undefined;

watch(search, (value) => {
    clearTimeout(timer);
    timer = setTimeout(() => {
        router.get(
            '/inventory',
            { search: value || undefined },
            { preserveState: true, replace: true, only: ['items', 'filters'] },
        );
    }, 300);
});

function price(item: InventoryItem): string {
    return item.default_price
        ? formatMoney(item.default_price.amount, item.default_price.currency, page.props.locale)
        : '—';
}
</script>

<template>
    <AppLayout title="Inventory">
        <div class="space-y-4">
            <div class="flex flex-wrap items-center gap-3">
                <Input v-model="search" placeholder="Search name or SKU…" class="max-w-xs" />
                <span class="text-sm text-muted-foreground">{{ items.meta.total }} items</span>
                <Button v-if="can('inventory.manage')" href="/inventory/new" class="ml-auto">New item</Button>
            </div>

            <!-- The table scrolls inside its own container so the page never does. -->
            <div class="overflow-x-auto rounded-xl border border-border bg-card">
                <table class="w-full min-w-[48rem] text-sm">
                    <thead class="border-b border-border text-left text-muted-foreground">
                        <tr>
                            <th scope="col" class="px-4 py-3 font-medium">Item</th>
                            <th scope="col" class="px-4 py-3 font-medium">SKU</th>
                            <th scope="col" class="px-4 py-3 font-medium">Category</th>
                            <th scope="col" class="px-4 py-3 text-right font-medium">Stock</th>
                            <th scope="col" class="px-4 py-3 text-right font-medium">Price</th>
                            <th scope="col" class="px-4 py-3 font-medium">Status</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-border">
                        <tr
                            v-for="item in items.data"
                            :key="item.id"
                            class="cursor-pointer hover:bg-accent/50"
                            @click="router.visit(`/inventory/${item.id}`)"
                        >
                            <td class="px-4 py-3 font-medium">{{ item.name }}</td>
                            <td class="px-4 py-3 text-muted-foreground">{{ item.sku }}</td>
                            <td class="px-4 py-3 text-muted-foreground">{{ item.category }}</td>
                            <td class="px-4 py-3 text-right tabular-nums">{{ item.current_stock }}</td>
                            <td class="px-4 py-3 text-right tabular-nums">{{ price(item) }}</td>
                            <td class="px-4 py-3">
                                <Badge :variant="item.is_active ? 'success' : 'neutral'">
                                    {{ item.is_active ? 'Active' : 'Inactive' }}
                                </Badge>
                            </td>
                        </tr>
                        <tr v-if="items.data.length === 0">
                            <td colspan="6" class="px-4 py-10 text-center text-muted-foreground">
                                No items match these filters.
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div v-if="items.meta.last_page > 1" class="flex items-center justify-between text-sm">
                <span class="text-muted-foreground">
                    Page {{ items.meta.current_page }} of {{ items.meta.last_page }}
                </span>
                <div class="flex gap-2">
                    <Button
                        variant="outline"
                        size="sm"
                        :disabled="items.meta.current_page <= 1"
                        @click="router.get('/inventory', { ...filters, page: items.meta.current_page - 1 })"
                    >
                        Previous
                    </Button>
                    <Button
                        variant="outline"
                        size="sm"
                        :disabled="items.meta.current_page >= items.meta.last_page"
                        @click="router.get('/inventory', { ...filters, page: items.meta.current_page + 1 })"
                    >
                        Next
                    </Button>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
